import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser, isAdmin } from '@/lib/auth';
import { sql } from '@vercel/postgres';
import { getDb } from '@/lib/db';

export async function GET(request: NextRequest) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const admin = await isAdmin(user.id);
  if (!admin) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  await getDb();

  try {
    const { searchParams } = new URL(request.url);
    const metric = searchParams.get('metric') || 'user-growth';

    if (metric === 'user-growth') {
      // Get user growth over last 30 days
      const result = await sql`
        SELECT
          DATE(created_at) as date,
          COUNT(*) as count
        FROM users
        WHERE created_at >= NOW() - INTERVAL '30 days'
        GROUP BY DATE(created_at)
        ORDER BY date ASC
      `;

      const cumulativeData = result.rows.reduce((acc: any[], row: any) => {
        const lastCount = acc[acc.length - 1]?.cumulative || 0;
        const dailyCount = parseInt(row.count, 10) || 0;
        acc.push({
          date: row.date,
          cumulative: lastCount + dailyCount,
          daily: dailyCount,
        });
        return acc;
      }, []);

      return NextResponse.json({ data: cumulativeData });
    } else if (metric === 'content-generated') {
      // Get content generated by type over last 30 days
      const result = await sql`
        SELECT
          content_type,
          DATE(created_at) as date,
          COUNT(*) as count
        FROM generated_content
        WHERE created_at >= NOW() - INTERVAL '30 days'
        GROUP BY content_type, DATE(created_at)
        ORDER BY date ASC, content_type
      `;

      // Transform to structured format using a lookup map instead of O(n) .find() per cell
      const contentTypes = new Set(result.rows.map((r: any) => r.content_type));
      const dates = new Set(result.rows.map((r: any) => r.date));
      const dateArray = Array.from(dates).sort();

      const lookup = new Map<string, number>();
      for (const r of result.rows) {
        lookup.set(`${r.date}|${r.content_type}`, parseInt(r.count, 10) || 0);
      }

      const data = dateArray.map((date) => {
        const obj: any = { date };
        contentTypes.forEach((type) => {
          obj[type] = lookup.get(`${date}|${type}`) ?? 0;
        });
        return obj;
      });

      return NextResponse.json({ data, contentTypes: Array.from(contentTypes) });
    } else if (metric === 'popular-content-types') {
      // Get all-time popular content types
      const result = await sql`
        SELECT
          content_type,
          COUNT(*) as count
        FROM generated_content
        GROUP BY content_type
        ORDER BY count DESC
      `;

      return NextResponse.json({ data: result.rows });
    } else if (metric === 'api-usage') {
      // Get API usage trends over last 30 days
      const result = await sql`
        SELECT
          event_type,
          DATE(created_at) as date,
          COUNT(*) as count
        FROM usage_events
        WHERE created_at >= NOW() - INTERVAL '30 days'
        GROUP BY event_type, DATE(created_at)
        ORDER BY date ASC, event_type
      `;

      // Transform to structured format using a lookup map instead of O(n) .find() per cell
      const eventTypes = new Set(result.rows.map((r: any) => r.event_type));
      const dates = new Set(result.rows.map((r: any) => r.date));
      const dateArray = Array.from(dates).sort();

      const lookup = new Map<string, number>();
      for (const r of result.rows) {
        lookup.set(`${r.date}|${r.event_type}`, parseInt(r.count, 10) || 0);
      }

      const data = dateArray.map((date) => {
        const obj: any = { date };
        eventTypes.forEach((type) => {
          obj[type] = lookup.get(`${date}|${type}`) ?? 0;
        });
        return obj;
      });

      return NextResponse.json({ data, eventTypes: Array.from(eventTypes) });
    } else if (metric === 'subscription-breakdown') {
      // Get subscription breakdown by plan
      const result = await sql`
        SELECT
          p.name as plan_name,
          COUNT(s.id) as count
        FROM subscriptions s
        JOIN subscription_plans p ON s.plan_id = p.id
        WHERE s.status = 'active'
        GROUP BY p.name
        ORDER BY count DESC
      `;

      return NextResponse.json({ data: result.rows });
    }

    return NextResponse.json({ error: 'Invalid metric' }, { status: 400 });
  } catch (error) {
    console.error('Analytics error:', error);
    return NextResponse.json({ error: 'Failed to fetch analytics' }, { status: 500 });
  }
}
